### ISSUE TITLE
No Menu Entry

### ISSUE THREAD

**Issue by itsNue** [jaredallard/notion-app#8]
I installed Notion on POP OS. But It doesn't create a menu entry. I have to run 'notion' in the installed directory in a terminal to launch notion.

**Comment by rafamadriz** [comment]
> I installed Notion on POP OS. But It doesn't create a menu entry. I have to run 'notion' in the installed directory in a terminal to launch notion.

I don't know if this will help at this point (it's been a long time since you posted this), however this may be helpful in the future for you and for other people.  

In Gnome there isn't a default option in the settings for adding launchers, so there's two options.

**1.** the first one is creating a desktop file in /usr/share/applications/ .Here's an example for the syntax

```
[Desktop Entry]
# The type as listed above
Type=Application
# The version of the desktop entry specification to which this file complies
Version=1.0
# The name of the application
Name=Name of Launcher
# A comment which can/will be used as a tooltip
Comment=A cool script that does cool stuff
# The path to the folder in which the executable is run
Path=/path/to/script/
# The executable of the application, possibly with arguments.
Exec=/path/to/script/scriptName
# The name of the icon that will be used to display this entry
Icon=iconName
# Describes whether this application needs to be run in a terminal or not
Terminal=false
# Describes the categories in which this entry should be shown
Categories=Education;Languages;Java;    
```

**However this is not user friendly at all and there's a better way of doing this** 

**2.** The second choice is by downloading and app which allows to edit the gnome menu.

`sudo apt install alacarte`

or you can just go to the popshop and get it from there.

Once you've downloaded the app when you opened it should show something similar to this
![image](https://user-images.githubusercontent.com/67771985/95689651-97adcc80-0be8-11eb-90b2-56dbe9fce877.png)

Just click on new item and you'll have this window 
![image](https://user-images.githubusercontent.com/67771985/95689679-cc218880-0be8-11eb-9bd5-759c39535e10.png)

In this case the name will be Notion and the command is the same you use on your terminal (notion). Finally click on the icon and add the png file that comes when you did the git clone.

Done!!! in theory you should have your Notion app in the menu.

**Comment by itsNue** [comment]
Nice man.Thanks for the help.

**Comment by giovaniif** [comment]
> > I installed Notion on POP OS. But It doesn't create a menu entry. I have to run 'notion' in the installed directory in a terminal to launch notion.
> 
> I don't know if this will help at this point (it's been a long time since you posted this), however this may be helpful in the future for you and for other people.
> 
> In Gnome there isn't a default option in the settings for adding launchers, so there's two options.
> 
> **1.** the first one is creating a desktop file in /usr/share/applications/ .Here's an example for the syntax
> 
> [Desktop Entry]
> 
> // The type as listed above
> Type=Application
> 
> // The version of the desktop entry specification to which this file complies
> Version=1.0
> 
> // The name of the application
> Name=Name of Launcher
> 
> // A comment which can/will be used as a tooltip
> Comment=A cool script that does cool stuff
> 
> // The path to the folder in which the executable is run
> Path=/path/to/script/
> 
> // The executable of the application, possibly with arguments.
> Exec=/path/to/script/scriptName
> 
> // The name of the icon that will be used to display this entry
> Icon=iconName
> 
> // Describes whether this application needs to be run in a terminal or not
> Terminal=false
> 
> // Describes the categories in which this entry should be shown
> Categories=Education;Languages;Java;
> 
> **However this is not user friendly at all and there's a better way of doing this**
> 
> **2.** The second choice is by downloading and app which allows to edit the gnome menu.
> 
> `sudo apt install alacarte`
> 
> or you can just go to the popshop and get it from there.
> 
> Once you've downloaded the app when you opened it should show something similar to this
> ![image](https://user-images.githubusercontent.com/67771985/95689651-97adcc80-0be8-11eb-90b2-56dbe9fce877.png)
> 
> Just click on new item and you'll have this window
> ![image](https://user-images.githubusercontent.com/67771985/95689679-cc218880-0be8-11eb-9bd5-759c39535e10.png)
> 
> In this case the name will be Notion and the command is the same you use on your terminal (notion). Finally click on the icon and add the png file that comes when you did the git clone.
> 
> Done!!! in theory you should have your Notion app in the menu.

Wow nice man! This helped me a lot.

**Comment by giovaniif** [comment]
Isn'it something that could be described in the docs?
